  
name: flutterando
description: Uma das maiores comunidade de Flutter do mundo.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  localization:
    git: 
      url: https://github.com/raphaelbarbosaqwerty/localization
      ref: fix_support_web
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

 
